# .github/workflows/build.yml
name: Build and Push Docker Image

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest ./app

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
