# .github/workflows/build.yml
name: Build and Push Docker Image

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/build.yml"
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOCKEN }}" | docker login ghcr.io -u bgarciau --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/bgarciau/${{ github.event.repository.name }}:latest ./app

      - name: Push Docker image
        run: docker push ghcr.io/bgarciau/${{ github.event.repository.name }}:latest
