# .github/workflows/deploy-monitoring.yml
name: Deploy Monitoring

on:
  push:
    paths:
      - "monitoring/**"
      - ".github/workflows/deploy-monitoring.yml"
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect and deploy monitoring
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/monitoreo-grafana-y-prometeus
            git pull
            docker-compose up -d prometheus grafana

