# .github/workflows/deploy-app.yml
name: Deploy App via SSH

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "docker-compose.yaml"
      - ".github/workflows/deploy-app.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/monitoreo-grafana-y-prometeus || git clone https://github.com/bgarciau/monitoreo-grafana-y-prometeus.git && cd monitoreo-grafana-y-prometeus
            git pull
            docker-compose stop app || true
            docker-compose rm -f app || true
            docker-compose pull app
            docker-compose up -d app
